# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '168彩' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 168彩
  pod 'AFNetworking'
  pod 'YYCache'
  pod 'YYModel'
  pod 'TACategorys', :git=>'https://github.com/tasama/TACategorys.git'
end

